---
title: "Creating Machine-Readable Documents from HTML"
author: "Andrew Kim and Olivia Xu"
date: "November 22, 2016"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 

# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
library(XML)
library(readr)
library(stringr)
```

# Appendix A

Before our analysis, we need to convert the HTML versions of Katherine Mansfield's works into machine-readable formats. This appendix will demonstrate how we are able to convert such text data into the approrpiate format.

```{r}
# Function that creates URLs for each story
createURL <- function(nums, site){
  x <- c()
  for(i in 1:length(nums)){
    y <- paste(site, nums[i], ".html", sep = "")
    x <-c(x, y)
  }
  return(x)
}

# Function that converts HTML to text file for each story
createTextfile <- function(site){
  name <- deparse(substitute(site))
  for(i in 1:length(site)){
    html <- getURL(site[i], followlocation = TRUE)
  
    # parse html
    doc = htmlParse(html, encoding = "UTF-8", asText=TRUE)
    title <- xpathSApply(doc, "//title", xmlValue)
    plain.text <- xpathSApply(doc, "//p", xmlValue)
    plain.text <- c(title, plain.text)
    cat(paste(plain.text, collapse = "\n"), file = paste(name, ".", i, ".txt", sep = ""), sep = "")
  }
}

# Read and parse HTML file
somethingChildishURL <- "https://ebooks.adelaide.edu.au/m/mansfield/katherine/something/chapter"
blissURL <- "https://ebooks.adelaide.edu.au/m/mansfield/katherine/bliss/chapter"
gardenPartyURL <- "https://ebooks.adelaide.edu.au/m/mansfield/katherine/garden/chapter"

somethingChildishChapterNum <- as.character(seq(1:25))
blissChapterNum <- as.character(seq(1:14))
gardenPartyChapterNum <- as.character(seq(1:15))

# create URLs for all stories
bliss <- createURL(blissChapterNum, blissURL)
somethingChildish <- createURL(somethingChildishChapterNum, somethingChildishURL)
gardenParty <- createURL(gardenPartyChapterNum, gardenPartyURL)

# store text files into separate folder
setwd("~/git/STAT495-Group6/textFiles")
createTextfile(bliss)
createTextfile(somethingChildish)
createTextfile(gardenParty)
```

